{"name": "Создание заказа с авторизацией", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код: {\"success\":false,\"message\":\"jwt malformed\"}\nassert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_order.TestOrders object at 0x0000022726008F50>\nauth_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDQyNTA2OWVkMjgwMDAxYjZhOTgxMSIsImlhdCI6MTc1ODczMzU3NSwiZXhwIjoxNzU4NzM0Nzc1fQ.7e_ZE31FY7l09iFjCh6a-eeSY65PROq8tTDJ4XZUDXU'\n\n    @allure.title(\"Создание заказа с авторизацией\")\n    def test_create_order_with_auth(self, auth_token):\n    \n        ingredients = get_ingredients()\n    \n        with allure.step(\"Создание заказа через API с токеном\"):\n            response = create_order(ingredients, auth_token)\n    \n        with allure.step(\"Проверка успешного ответа\"):\n>           assert response.status_code == 200, f\"Неверный код: {response.text}\"\nE           AssertionError: Неверный код: {\"success\":false,\"message\":\"jwt malformed\"}\nE           assert 403 == 200\nE            +  where 403 = <Response [403]>.status_code\n\ntests\\test_order.py:18: AssertionError"}, "steps": [{"name": "Получение списка ингредиентов", "status": "passed", "start": 1758733575890, "stop": 1758733576384}, {"name": "Создание заказа через API с токеном", "status": "passed", "steps": [{"name": "Создание заказа с ингредиентами: ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa6f', '61c0c5a71d1f82001bdaaa70', '61c0c5a71d1f82001bdaaa71', '61c0c5a71d1f82001bdaaa72', '61c0c5a71d1f82001bdaaa6e', '61c0c5a71d1f82001bdaaa73', '61c0c5a71d1f82001bdaaa74', '61c0c5a71d1f82001bdaaa6c', '61c0c5a71d1f82001bdaaa75', '61c0c5a71d1f82001bdaaa76', '61c0c5a71d1f82001bdaaa77', '61c0c5a71d1f82001bdaaa78', '61c0c5a71d1f82001bdaaa79', '61c0c5a71d1f82001bdaaa7a']", "status": "passed", "start": 1758733576384, "stop": 1758733576844}], "start": 1758733576384, "stop": 1758733576844}, {"name": "Проверка успешного ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код: {\"success\":false,\"message\":\"jwt malformed\"}\nassert 403 == 200\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"C:\\Users\\dariy\\Diplom\\diplom_2\\tests\\test_order.py\", line 18, in test_create_order_with_auth\n    assert response.status_code == 200, f\"Неверный код: {response.text}\"\n"}, "start": 1758733576844, "stop": 1758733576844}], "start": 1758733575889, "stop": 1758733576849, "uuid": "047ed283-29ac-47f6-863c-65577e44a6bf", "historyId": "55f87d4d086a6d08a0131e7b60f83545", "testCaseId": "55f87d4d086a6d08a0131e7b60f83545", "fullName": "tests.test_order.TestOrders#test_create_order_with_auth", "labels": [{"name": "feature", "value": "Заказы"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrders"}, {"name": "host", "value": "DARIYA"}, {"name": "thread", "value": "12060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}], "titlePath": ["tests", "test_order.py", "TestOrders"]}